#!/bin/bash

mkdir -p /var/db/repos/crossdev/{profiles,metadata}
echo crossdev >/var/db/repos/crossdev/profiles/repo_name
echo 'masters = gentoo' >/var/db/repos/crossdev/metadata/layout.conf
chown -R portage:portage /var/db/repos/crossdev

mkdir /etc/portage/repos.conf
cp configs/crossdev.conf /etc/portage/repos.conf/

emerge -j4 -v sys-devel/bc sys-devel/crossdev dev-vcs/git app-portage/gentoolkit

crossdev --stage1 --target m68k-elf

eclean distfiles
